require: rubocop-rspec
AllCops:
  TargetRubyVersion: 2.6.2
AccessorMethodName:
  Enabled: false
AmbiguousRegexpLiteral:
  Enabled: false
Documentation:
  Enabled: false
Encoding:
  Enabled: false
Layout/CommentIndentation:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/IndentHeredoc:
  EnforcedStyle: squiggly
Layout/MultilineArrayLineBreaks:
  Enabled: true
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Lint/InheritException:
  Enabled: false
Lint/HandleExceptions:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/CyclomaticComplexity:
  Enabled: false
Metrics/LineLength:
  AutoCorrect: true
  Max: 80
Metrics/MethodLength:
  Enabled: false
Metrics/PerceivedComplexity:
  Enabled: false
NumericLiterals:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/EmptyMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/MultilineBlockChain:
  Enabled: false
Style/RaiseArgs:
  Enabled: false
Style/Semicolon:
  Enabled: false
