source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.6.2'

gem 'rails', '= 5.2.3'

gem 'awesome_print',            '~> 1.8.0', group: %i[development test]
gem 'bcrypt',                   '~> 3.1.12'
gem 'better_errors',            '~> 2.5.1', group: %i[development]
gem 'binding_of_caller',        '= 0.8.0', group: %i[development], platforms: %i[mri]
gem 'bootsnap',                 '~> 1.4.3', require: false
gem 'brakeman',                 '~> 4.5.0', group: %i[development]
gem 'bullet',                   '~> 5.9.0', group: %i[development]
gem 'bundler-audit',            '= 0.6.1', group: %i[development]
gem 'byebug',                   '~> 11.0.1', group: %i[development test], platforms: %i[mri]
gem 'capybara',                 '~> 3.18.0', group: %i[test]
gem 'dotenv-rails',             '~> 2.7.2', group: %i[development test]
gem 'factory_bot_rails',        '~> 5.0.2', group: %i[development test]
gem 'faker',                    '~> 1.9.3', group: %i[test]
gem 'jbuilder',                 '~> 2.8.0'
gem 'launchy',                  '~> 2.4.3', group: %i[test]
gem 'listen',                   '~> 3.1.5', group: %i[development]
gem 'pg',                       '~> 1.1.4'
gem 'pry-byebug',               '~> 3.7.0', group: %i[development test], platforms: %i[mri]
gem 'pry-rails',                '= 0.3.9', group: %i[development test]
gem 'puma',                     '~> 3.12.1'
gem 'rails-controller-testing', '~> 1.0.4', group: %i[test]
gem 'rspec-rails',              '~> 3.8.2', group: %i[development test]
gem 'rubocop',                  '= 0.67.2', group: %i[development test], require: false
gem 'shoulda-matchers',         '~> 4.0.1', group: %i[test]
gem 'simplecov',                '= 0.16.1', group: %i[test], require: false
gem 'spring',                   '~> 2.0.2', group: %i[development]
gem 'spring-commands-rspec',    '~> 1.0.4', group: %i[development]
gem 'spring-watcher-listen',    '~> 2.0.1', group: %i[development]
gem 'timecop',                  '= 0.9.1', group: %i[test]
gem 'webmock',                  '~> 3.5.1', group: %i[test]
